# Generated by Django 4.2 on 2023-09-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0002_rename_flag_url_country_flag_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pays', models.CharField(max_length=200)),
                ('drapeau', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
