# Generated by Django 4.2 on 2023-09-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0003_pays_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_league', models.IntegerField(max_length=11)),
                ('nom_league', models.CharField(max_length=200)),
                ('logo', models.URLField()),
                ('pays', models.CharField(max_length=200)),
                ('flags', models.URLField(null=True)),
                ('annee', models.DateField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('currently', models.BooleanField(default=False)),
            ],
        ),
    ]
