# Generated by Django 4.2 on 2023-09-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0004_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='types',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='id_league',
            field=models.IntegerField(),
        ),
    ]
