# Generated by Django 4.2 on 2023-09-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0005_league_types_alter_league_id_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='annee',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='league',
            name='date_debut',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='league',
            name='date_fin',
            field=models.CharField(max_length=200),
        ),
    ]
